[package]
name = "bodyproblem"
version = "0.1.0"
edition = "2024"

[dependencies]
piston = "0.53.2"
piston2d-graphics = "0.43.0"
piston2d-opengl_graphics = "0.82.0"
pistoncore-glutin_window = "0.71.0"
